config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  delete '/posts/:id', to: 'posts#destroy'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  resources :users, only: [:new, :create]
  resources :posts do 
      resources :comments, only: [:create]
  end 

  resources :post, only: [:delete]
  delete 'logout', to: 'sessions#destroy'


  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :text
#  post_id    :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id                 :integer          not null, primary key
#  title              :string
#  description        :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_file_name    :string
#  image_content_type :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#  user_id            :integer
#

class Post < ApplicationRecord

  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :user, presence: true
  validates :title, presence: true
  validates :description, presence: true,  length: { minimum: 250 }


  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/


end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(100)
#  password_digest :string
#  name            :string(100)
#  username        :string(100)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_secure_password validations: false

    validates :email, uniqueness: true, format: /@/
    validates :password, presence: true, on: :create
    validates :password, length: { in: 6..20 }, allow_nil: true
    validates :name, presence: true
    validates :username, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

def private_access
  redirect_to :login unless signed_in?
end

def sign_in(user)
    cookies.permanent.signed[:user_id] = user.id
    @current_user = user
end 


def sign_out 
    cookies.delete(:user_id)
    @current_user = nil
end 

    
private
    def signed_in?
        !current_user.nil?
    end 
    helper_method :signed_in?

  def current_user
    @current_user ||= User.find(cookies.signed[:user_id]) if cookies.signed[:user_id]
  rescue ActiveRecord::RecordNotFound
  end
  helper_method :current_user


  def public_access
  redirect_to root_path if signed_in?
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @post.comments.create(comments_params)

    redirect_to @post
  end

  private 
  def comments_params
      params.require(:comment).permit(:body).merge(user: current_user)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :private_access, except: [:index, :show]
   
    def index
      @posts = if params[:term]
      Post.where("title iLIKE ? OR description iLIKE ?" , "%#{params[:term]}%", "%#{params[:term]}%")
      else
      @posts = Post.all.order("updated_at DESC")
      end 
    end

    def show
     @post = Post.find(params[:id])        
    end 

    def new
     @post = Post.new
    end 

    def create
      @post = Post.new(post_params)
      @post.user = current_user
     if @post.save
      flash[:success] = "Fabuloso! Has creado un nuevo post....!"
      redirect_to posts_path
     else 
      render :new
     end 
    end

    def edit
       @post = Post.find(params[:id])      
    end

    def update
       @post = Post.find(params[:id])
         if @post.update(post_params)
          flash[:success] = "Bravo! Post fue editado..."
          redirect_to posts_path
         else 
          render :edit
         end 
    end

 
     def destroy
        post = Post.find(params[:id])
        if post.destroy
        flash[:danger] = "El post fue eliminado con éxito"
        redirect_to posts_path
        else  
        flash[:danger] = "Habia un error. Por favor intenta otra vez..."
        end
     end 
  
     private
     def post_params
        params.require(:post).permit(:title, :description, :id, :image, :term)
     end 
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :private_access, only: [:destroy]
  before_action :public_access, except: [:destroy]

  def create
    user = User.find_by(email: params[:email])
      if user && user.authenticate(params[:password])
        sign_in(user)
        flash[:success] = "Bienvenido pana! Entraste exitosamente"
        redirect_to root_path
      else
        flash.now[:danger] = "Tu email y/o contraseña son inválidas. Intenta nuevamente."
        render :new
      end
  end

  def destroy  
    sign_out
    flash[:warning] = "Hasta Luego, para que vuelvas pronto..."
    redirect_to root_path
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new 
      @user = User.new
    end 

    def create
     @user = User.new(user_params)
      if @user.save
          session[:user_id] = @user.id
          flash[:success] = "Bacano! Creaste una Cuenta! Ahora puedes compartir con la communidad..."
          redirect_to posts_path
      else
        render :new
      end
    end

  private
    def user_params
      params.require(:user).permit(:email, :password, :name, :username)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper

     def markdown(text)
      options = {
        filter_html:     true,
        hard_wrap:       true,
        link_attributes: { rel: 'nofollow', target: "_blank" },
        space_after_headers: true,
        fenced_code_blocks: true
      }

      extensions = {
        autolink:           true,
        superscript:        true,
        disable_indented_code_blocks: true
      }

      renderer = Redcarpet::Render::HTML.new(options)
      markdown = Redcarpet::Markdown.new(renderer, extensions)

      markdown.render(text).html_safe
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def form_title
    @post.new_record? ? "Publish Post" : "Modify Post"
  end

  def header_style 
     if @post.image.exists?
    %{ style="background-image: linear-gradient(rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2) ), url('#{@post.image.url}'); height:100%; background-position:center; background-repeat:no-repeat; background-size:cover" }.html_safe
      
    else
    %{ style="background-image: linear-gradient(rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2) ), url('https://images.pexels.com/photos/37728/pexels-photo-37728.jpeg?cs=srgb&dl=above-atmosphere-clouds-37728.jpg&fm=jpg'); height:100%; background-position:center; background-repeat:no-repeat; background-size:cover" }.html_safe
    end 
  end 
end 

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Superblog</title>
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
          <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
</head>

<body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "Super City Blog", root_path, class: "navbar-brand" %>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if signed_in? %>
                <li>
                  <a href="#" class="avatar">
                    <img src="<%= Gravatar.new(" #{current_user.email} ").image_url %>" class="img-circle" />
                  </a>
                </li>
                <li id="glyph">
                  <%= link_to "<span class='glyphicon glyphicon-plus'></span>".html_safe, new_post_path %>
                </li>
                <li>
                  <%= link_to "<span class='glyphicon glyphicon-off'></span>".html_safe, logout_path, method: :delete %>
                </li>
                <% else %>
                  <li>
                    <%= link_to "Regístrate", new_user_path %>
                  </li>
                  <li>
                    <%= link_to "Entrar", login_path %>
                  </li>
                  <% end %>
            </ul>
            <div class="searchbar">
              <%= form_tag(posts_path, method: :get) do %>
                <%= text_field_tag :term%>
                  <div class="tag">
                    <%= submit_tag 'search'%>
                  </div>
                  <% end %>
            </div>
          </div>
          <!-- /.navbar-collapse -->
        </div>
      </div>
      <!-- /.container -->
  </nav>


  <div class "alert">
    <% flash.each do |key, value| %>
      <div class='alert alert-<%=key%>'>
        <%= value %>
      </div>
      <% end %>
  </div>

  <%= yield %>
</body>

</html>

app/views/posts/_form.html.erb
<div class="allposts">
 <div class="container">
   <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <%= form_for @post do |f| %>
      <br> <br>
      <h1 class="form-title"><%= form_title %></h1>
        <% if @post.errors.any?  %>
        <div class="aler alert-danger">
        <ul>
        <% @post.errors.full_messages.each do |msg| %>
        <li> <%= msg %> <s/li>
        <% end %>
        </ul>
        </div>
        <% end  %>

        <div class="letter-form">
            <%= f.label :City %>
        </div>
        <div class="form-group">
          <%= f.text_field :title, class:"form-control", placeholder:"Nombre de la ciudad"%>
        </div>
        <div class="letter-form">
          <%= f.label :Descripción %>
        </div> 
        <div class="form-group">
        <%= f.text_area :description, rows:15, class:"form-control", placeholder: "Cuentanos un poco sobre la ciudad o el lugar especial"%>
        </div>
        <div class="letter-form">
          <%= f.label :Imágen %>
        </div>
        <div class="letter-form"> 
        <%= f.file_field :image %>
        </div>          
        <div class="text-center">
        <%= f.submit class: 'btn btn-default' %>
        </div>
      <% end %>
     </div>
   </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render  "form" %>

app/views/posts/index.html.erb
<% @posts.each do  |post|%>
  <div class="allposts">
    <br>
    <br>
    <div class="post-title">
      <%= link_to post.title, post%>
    </div>
    <p class="username"> Gracias <span class="name"> <%= post.user.name %> </span> para compartir este bonito lugar (fue publicado <%= l(post.created_at, format: :long) %>) </p>
    
    <div class="description">
      <span class="post-description">
        <%= markdown(truncate(post.description, :length => 250 , :seperator => ' ')) %>
      </span>
    </div>

    <% if signed_in? && post.user == current_user %>
      <br>
      <div>
       <%= link_to  "<span class='glyphicon glyphicon-pencil'></span>".html_safe, edit_post_path(post) %>
       <%= link_to "<span class='glyphicon glyphicon-trash'></span>".html_safe, post, method: :delete, data: { confirm: "¿Estás seguro de eliminar este producto?" } %>
      </div>
      <% end %>
    <% end %>

    <% if signed_in? %>
        <br>
      <div class="text-center">
      <%= link_to "Nuevo Post", new_post_path, class: "btn btn-default" %>
      </div>
      <% end %>
       <div>
        <br>
        <br>

app/views/posts/new.html.erb
<%= render  "form" %>

app/views/posts/show.html.erb
<header class="post-header" <%= header_style %>> 
  <div class="container">
    <div class="row">
    <br>
      <h1 class="post-head"> Eso es:  <%= @post.title %> </h1>
    <div class="post-page">
      <p><%= markdown(@post.description) %></p>
   </div>
<br>
  <% @post.comments.each do |comment| %>
  <div class="panel panel-default">
    <header class="panel-heading"> <%= comment.user.name %> escribió:  </header>
    <div class="panel-body"><%= markdown(comment.body) %></div>
  </div>
  <% end %>

<% if signed_in? %>
  <%= form_for [@post, @post.comments.build] do |f| %>
   <div class="formular">
      <div class="form-group">
        <%= f.text_area :body, class: "form-control", placeholder: "Agregar comentario" %>
      </div>
      <div class="actions text-right">
        <%= f.submit "Comentar", class: "btn btn-default" %>
      </div>
    </div>
  <% end %>
<% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="allposts">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
      <br>
      <h1 class="user-heading">Crear una Cuenta</h1>
        <% if @user.errors.any? %>
        <div class="alert alert-danger">
          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
        <% end %>
      <br>
      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.email_field :email, class: "form-control input-lg", placeholder: "Email" %>
        </div>
        <div class="form-group">
          <%= f.password_field :password, class: "form-control input-lg", placeholder: "Contraseña" %>
        </div>
        <div class="form-group">
          <%= f.text_field :name, class: "form-control input-lg", placeholder: "Name" %>
        </div>
        <div class="form-group">
          <%= f.text_field :username, class: "form-control input-lg", placeholder: "Nickname" %>
        </div>
        <div class="actions">
          <%= f.submit 'Crear Usario', class: "btn btn-primary btn-block btn-lg" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>